"""add fetched_at and withdrawn_at fields

Revision ID: 1d779893ad98
Revises: 4431cd2ad0bb
Create Date: 2026-09-07 12:42:50.170941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d779893ad98'
down_revision: Union[str, Sequence[str], None] = '4431cd2ad0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jvn_vulnerabilities', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('osv_vulnerabilities', sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('osv_vulnerabilities', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vulnerabilities', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'fetched_at')
    op.drop_column('osv_vulnerabilities', 'fetched_at')
    op.drop_column('osv_vulnerabilities', 'withdrawn_at')
    op.drop_column('jvn_vulnerabilities', 'fetched_at')
    # ### end Alembic commands ###
