"""add compatibility_badge_url to dependabot_pr_logs

Revision ID: 37dbc45956fd
Revises: 89150368e591
Create Date: 2026-09-09 06:10:30.913131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37dbc45956fd'
down_revision: Union[str, Sequence[str], None] = '89150368e591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependabot_pr_logs', sa.Column('compatibility_badge_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependabot_pr_logs', 'compatibility_badge_url')
    # ### end Alembic commands ###
