"""add EPSS score fields to vulnerabilities

Revision ID: 4431cd2ad0bb
Revises: eac4893a0796
Create Date: 2026-09-06 18:57:07.995303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4431cd2ad0bb'
down_revision: Union[str, Sequence[str], None] = 'eac4893a0796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('epss_score', sa.Float(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('epss_percentile', sa.Float(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('epss_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'epss_updated_at')
    op.drop_column('vulnerabilities', 'epss_percentile')
    op.drop_column('vulnerabilities', 'epss_score')
    # ### end Alembic commands ###
