"""add reachability field to dependency_findings

Revision ID: 6b92bffef4b1
Revises: 505622a59c87
Create Date: 2026-09-08 07:30:13.285173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b92bffef4b1'
down_revision: Union[str, Sequence[str], None] = '505622a59c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency_findings', sa.Column('reachability', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependency_findings', 'reachability')
    # ### end Alembic commands ###
