"""add is_security_update to dependabot_pr_logs

Revision ID: 89150368e591
Revises: 6b92bffef4b1
Create Date: 2026-09-08 20:07:57.260998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89150368e591'
down_revision: Union[str, Sequence[str], None] = '6b92bffef4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependabot_pr_logs', sa.Column('is_security_update', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependabot_pr_logs', 'is_security_update')
    # ### end Alembic commands ###
