"""add repo_visibility and repo_asset_contexts table

Revision ID: af0d41f61085
Revises: 37dbc45956fd
Create Date: 2026-09-12 13:05:10.494544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0d41f61085'
down_revision: Union[str, Sequence[str], None] = '37dbc45956fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_asset_contexts',
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('is_internet_facing', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('repo_full_name')
    )
    op.add_column('dependency_findings', sa.Column('repo_visibility', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependency_findings', 'repo_visibility')
    op.drop_table('repo_asset_contexts')
    # ### end Alembic commands ###
