"""add cve_ids to dependency_findings

Revision ID: d33e94df618f
Revises: af0d41f61085
Create Date: 2026-09-12 15:21:47.226857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33e94df618f'
down_revision: Union[str, Sequence[str], None] = 'af0d41f61085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='[]'を指定し、既存行への一括バックフィルなしでNOT NULL列を追加する
    # （新規追加のため既存行は元々CVE紐付けを持たないが、空配列で埋めておけばよい）
    op.add_column(
        'dependency_findings',
        sa.Column('cve_ids', sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependency_findings', 'cve_ids')
    # ### end Alembic commands ###
