"""baseline: initial schema before EPSS

Revision ID: eac4893a0796
Revises: 
Create Date: 2026-09-06 18:56:35.222556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac4893a0796'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crawler_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawler_logs_crawler_type', 'crawler_logs', ['crawler_type'], unique=False)
    op.create_index('ix_crawler_logs_started_at', 'crawler_logs', ['started_at'], unique=False)
    op.create_table('dependency_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('installed_version', sa.String(length=100), nullable=False),
    sa.Column('osv_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fixed_versions', sa.JSON(), nullable=False),
    sa.Column('manifest_path', sa.String(length=500), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_full_name', 'ecosystem', 'package_name', 'osv_id', name='uq_dependency_findings')
    )
    op.create_index('ix_dependency_findings_repo', 'dependency_findings', ['repo_full_name'], unique=False)
    op.create_index('ix_dependency_findings_resolved_at', 'dependency_findings', ['resolved_at'], unique=False)
    op.create_index('ix_dependency_findings_severity', 'dependency_findings', ['severity'], unique=False)
    op.create_table('depscan_user_scans',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('repos_scanned', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('jvn_vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jvndb_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('cve_ids', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('jvn_url', sa.String(length=500), nullable=False),
    sa.Column('date_published', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jvndb_id', name='uq_jvn_vulnerabilities_jvndb_id')
    )
    op.create_index('ix_jvn_vulnerabilities_date_last_modified', 'jvn_vulnerabilities', ['date_last_modified'], unique=False)
    op.create_index('ix_jvn_vulnerabilities_severity', 'jvn_vulnerabilities', ['severity'], unique=False)
    op.create_table('osv_vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('osv_id', sa.String(length=50), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('affected_versions', sa.JSON(), nullable=False),
    sa.Column('fixed_versions', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osv_id', 'ecosystem', 'package_name', name='uq_osv_vulnerabilities')
    )
    op.create_index('ix_osv_vulnerabilities_ecosystem', 'osv_vulnerabilities', ['ecosystem'], unique=False)
    op.create_index('ix_osv_vulnerabilities_modified', 'osv_vulnerabilities', ['modified'], unique=False)
    op.create_index('ix_osv_vulnerabilities_severity', 'osv_vulnerabilities', ['severity'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=30), nullable=False),
    sa.Column('vendor_project', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('vulnerability_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id', name='uq_vulnerabilities_cve_id')
    )
    op.create_index('ix_vulnerabilities_date_added', 'vulnerabilities', ['date_added'], unique=False)
    op.create_index('ix_vulnerabilities_vendor_product', 'vulnerabilities', ['vendor_project', 'product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vulnerabilities_vendor_product', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_date_added', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index('ix_osv_vulnerabilities_severity', table_name='osv_vulnerabilities')
    op.drop_index('ix_osv_vulnerabilities_modified', table_name='osv_vulnerabilities')
    op.drop_index('ix_osv_vulnerabilities_ecosystem', table_name='osv_vulnerabilities')
    op.drop_table('osv_vulnerabilities')
    op.drop_index('ix_jvn_vulnerabilities_severity', table_name='jvn_vulnerabilities')
    op.drop_index('ix_jvn_vulnerabilities_date_last_modified', table_name='jvn_vulnerabilities')
    op.drop_table('jvn_vulnerabilities')
    op.drop_table('depscan_user_scans')
    op.drop_index('ix_dependency_findings_severity', table_name='dependency_findings')
    op.drop_index('ix_dependency_findings_resolved_at', table_name='dependency_findings')
    op.drop_index('ix_dependency_findings_repo', table_name='dependency_findings')
    op.drop_table('dependency_findings')
    op.drop_index('ix_crawler_logs_started_at', table_name='crawler_logs')
    op.drop_index('ix_crawler_logs_crawler_type', table_name='crawler_logs')
    op.drop_table('crawler_logs')
    # ### end Alembic commands ###
